function [control_force, control_memory_variable] = Control( ...
    control_memory_variable, ...
    relative_state_chaser, ...
    desired_relative_state, ...
    controller, ...
    time_step, ...
    mass, ...
    mean_motion ...
    )
    % MSAT Controll function
    % controller can be LQR, PID
    if strcmp('LQR', controller)
        [control_force, ~] = LQR_3D(relative_state_chaser, desired_relative_state, time_step, mass, mean_motion);
    elseif strcmp('PID', controller)
        control_force = [0; 0; 0];
    end
end